#!/bin/bash -x

echo "sorting arithmetic computation"
read-p " enter three inputs: " a b c
declare -A dict
dict[uc_2]=$(( $a + $b +$c ))
dict[uc_3]=$(( $a + $b +$c ))
dict[uc_4]=$(( $a + $b / $c ))
dict[uc_5]=$(( $a % $b + $c ))

echo "all the added elements of dict: " ${dict[@]}
echo "all the added elements of dict: " ${!dict[@]}
ct=0
fo value in ${dict[@]}

do
     array[$ct]=$value
     ct=$(( $ct -1 ))

done

echo "all value: " ${$array[@]}
asc=()


while [  ${$array[@] -gt 1 ]

do

first=$[{array[@]}

for i in ${array[@]}

if [ $# -eq 0 ]
then 
   echo "usage error: sh script _name arg1 arg2 ...."
else 
    if [ -f ${dict[@]} ]
  then
      rm dict[@]
fi


for i in ${dict[@]}

do 
    echo "$i" >> {dict[@]}
done

echo "dict elemnts in ascending order"
sort -nr {dict[@]}


