#!/bin/bash -x

echo "sorting arithmetic computation"
read-p " enter three inputs: " a b c
declare -A dict
dict[uc_2]=$(( $a + $b +$c ))
dict[uc_3]=$(( $a + $b +$c ))
dict[uc_4]=$(( $a + $b / $c ))
dict[uc_5]=$(( $a % $b + $c ))

echo "all the added elements of dict: " ${dict[@]}

