#!/bin/bash -x

echo "sorting arithmetic computation"
read-p " enter three inputs: " a b c
declare -A dict
dict[uc_2]=$(( $a + $b +$c ))
dict[uc_3]=$(( $a + $b +$c ))
dict[uc_4]=$(( $a + $b / $c ))
dict[uc_5]=$(( $a % $b + $c ))

echo "all the added elements of dict: " ${dict[@]}
echo "all the added elements of dict: " ${!dict[@]}
ct=0
fo value in ${dict[@]}

do
     array[$ct]=$value
     ct=$(( $ct -1 ))

done

echo "all value: " ${$array[@]}
asc=()
